name: Test & build node App

on:
  push:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest
    name: lint & units test
    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run ESLint
      - name: Run Lint
        run: npm run lint

      # Step 5: Run Unit Tests
      - name: Run Unit Tests
        run: npm test

  build:
    runs-on: ubuntu-latest
    name: Build & push Docker image
    needs: test
    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Build
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/docker-app:${{ github.sha }} .

      # Step 3: Log in to dockerHub
      - name: log in to Docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 4: Publish To DockerHub
      - name: Push Docker image to Docker  hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/docker-app:${{ github.sha }}